default_stages: [pre-commit, pre-push]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      # black-compatible formatter, Runs first so later lint hooks see the formatted code
      # picks up config from [tool.ruff] in pyproject.toml
      - id: ruff-format
        name: ruff-format (black-style)
        files: (?x)^project/(paperbench|swelancer|compatibility_api|compatibility_api_preparedness|preparedness_turn_completer)/

      # Lenient hook: runs auto‑fix on all files using a lenient config.
      - id: ruff
        name: ruff-lenient (auto-fix)
        args:
          - --config=./.ruff_autofix_minimal.toml
          - --unsafe-fixes
          - --exit-non-zero-on-fix
      
      # Strict hook: runs lint only on files opted-in projects (using strict config pulled from pyproject.toml)
      - id: ruff
        name: ruff-strict (lint)
        args:
          - --fix
          - --fix-only
          - --exit-non-zero-on-fix
        files: (?x)^project/(alcatraz|nanoeval|paperbench|swelancer|compatibility_api|compatibility_api_preparedness|preparedness_turn_completer)/

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.14
    hooks:
      - id: uv-lock
        name: uv-lock-paperbench
        args: [--project, project/paperbench]
        files: (?x)^project/paperbench/
      - id: uv-lock
        name: uv-lock-preparedness_turn_completer
        args: [--project, project/preparedness_turn_completer]
        files: (?x)^project/preparedness_turn_completer/
      - id: uv-lock
        name: uv-lock-swelancer
        args: [--project, project/swelancer]
        files: (?x)^project/swelancer/
exclude: '(?x)^(project/paperbench/paperbench/agents/aisi-basic-agent/inspect_ai|project/swelancer/issues)/'
