[project]
name = "preparedness_turn_completer"
version = "0.1.0"
dependencies = ["openai", "tenacity", "chz", "structlog", "tiktoken"]

[tool.setuptools]
packages = ["preparedness_turn_completer"]

[build-system]
requires = ["setuptools<78.0.0", "wheel"]
build-backend = "setuptools.build_meta"
