[project]
name = "nanoeval_alcatraz"
version = "0.1.0"
dependencies = ["async-lru", "structlog", "typing-extensions"]

[tool.setuptools.packages.find]
include = ["nanoeval_alcatraz*"]

[build-system]
requires = ["setuptools<78.0.0", "wheel"]
build-backend = "setuptools.build_meta"
