env-config-vars: &env-config-vars
  INSPECT_PY_LOGGER_FILE: /home/logs/inspect.log
  INSPECT_PY_LOGGER_LEVEL: DEBUG
  
# Common settings for all aisi-basic-agent configurations
common: &common_settings
  start: aisi-basic-agent/start.sh
  dockerfile: aisi-basic-agent/Dockerfile
  mount_docker_socket: true

# Dev configurations

aisi-basic-agent-openai-dev:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openai/gpt-4o-mini
    MAX_TIME_IN_HOURS: 0.1
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

aisi-basic-agent-anthropic-dev:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: anthropic/claude-3-5-haiku-latest
    MAX_TIME_IN_HOURS: 0.1
    ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

aisi-basic-agent-gemini-dev:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: google/gemini-1.5-pro-002
    MAX_TIME_IN_HOURS: 0.1
    GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

aisi-basic-agent-r1-dev:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openrouter/deepseek-ai/DeepSeek-R1
    MAX_TIME_IN_HOURS: 0.5
    OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

aisi-basic-agent-claude-3-7-sonnet-dev:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openrouter/anthropic/claude-3.7-sonnet:thinking
    MAX_TIME_IN_HOURS: 0.1
    OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

# OpenAI

aisi-basic-agent-4o:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openai/gpt-4o
    MAX_TIME_IN_HOURS: 12
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

aisi-basic-agent-o1:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openai/o1
    MAX_TIME_IN_HOURS: 12
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

aisi-basic-agent-o3-mini:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openai/o3-mini-2025-01-31
    MAX_TIME_IN_HOURS: 12
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

# Anthropic

aisi-basic-agent-claude-3-5-sonnet:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openrouter/anthropic/claude-3.5-sonnet
    MAX_TIME_IN_HOURS: 12
    OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

aisi-basic-agent-claude-3-7-sonnet:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openrouter/anthropic/claude-3.7-sonnet:thinking
    MAX_TIME_IN_HOURS: 12
    OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

# Google

aisi-basic-agent-gemini-2.0-flash:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: google/gemini-2.0-flash
    MAX_TIME_IN_HOURS: 12
    GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

# DeepSeek

aisi-basic-agent-r1:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openrouter/deepseek-ai/DeepSeek-R1
    MAX_TIME_IN_HOURS: 12
    OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

# IterativeAgent

aisi-basic-agent-iterative-o1:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openai/o1
    MAX_TIME_IN_HOURS: 12
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    ITERATIVE_AGENT: true

aisi-basic-agent-iterative-o3-mini:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openai/o3-mini-2025-01-31
    MAX_TIME_IN_HOURS: 12
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    ITERATIVE_AGENT: true

aisi-basic-agent-iterative-claude-3-5-sonnet:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openrouter/anthropic/claude-3.5-sonnet
    MAX_TIME_IN_HOURS: 12
    OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
    ITERATIVE_AGENT: true

aisi-basic-agent-iterative-claude-3-7-sonnet:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openrouter/anthropic/claude-3.7-sonnet:thinking
    MAX_TIME_IN_HOURS: 12
    OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
    ITERATIVE_AGENT: true

aisi-basic-agent-iterative-o1-pb-code-only:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openai/o1
    MAX_TIME_IN_HOURS: 12
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    ITERATIVE_AGENT: true
    PB_CODE_ONLY: "true"
